---
title: El operando 'Throw' debe derivar de 'System.Exception'
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 92fccbd2faac5580d28fef8cc02b51b23715f136
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414951"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>El operando 'Throw' debe derivar de 'System.Exception'
El argumento proporcionado a `Throw` debe ser una instancia de `System.Exception` o una instancia de una clase derivada de `System.Exception`.  
  
 **Identificador de error:** BC30665  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
- Use un argumento derivado de `System.Exception`, como en el ejemplo siguiente.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>Consulte también

- [Throw (instrucción)](../language-reference/statements/throw-statement.md)
- [Instrucción Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Controlar y generar excepciones en .NET](../../standard/exceptions/index.md)
