---
description: Advertencia del compilador (nivel 1) CS1058
title: Advertencia del compilador (nivel 1) CS1058
ms.date: 07/20/2015
f1_keywords:
- CS1058
helpviewer_keywords:
- CS1058
ms.assetid: ed50590c-f130-47c3-976d-322a6c8f996d
ms.openlocfilehash: 77097472f95d636a6ebc79a5a86083042a48ca32
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 08/30/2020
ms.locfileid: "89139130"
---
# <a name="compiler-warning-level-1-cs1058"></a>Advertencia del compilador (nivel 1) CS1058
Una cláusula catch previa ya detecta todas las excepciones. Todas las excepciones producidas se ajustarán en System.Runtime.CompilerServices.RuntimeWrappedException  
  
 Este atributo provoca una advertencia CS1058 si un bloque `catch()` no tiene ningún tipo de excepción especificado después de un bloque `catch (System.Exception e)`. La advertencia le avisa de que el bloque `catch()` no capturará ninguna excepción.  
  
Un bloque `catch()` después de un bloque `catch (System.Exception e)` puede capturar excepciones de no compatibilidad con CLS si `RuntimeCompatibilityAttribute` se establece en False en el archivo AssemblyInfo.cs: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`. Si este atributo no se establece explícitamente en False, todas las excepciones de no compatibilidad con CLS generadas se ajustan como excepciones y el bloque `catch (System.Exception e)` las detecta. Para más información, consulte [Procedimiento para detectar excepciones no compatibles con CLS](../../programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).
  
## <a name="example"></a>Ejemplo  
 En el ejemplo siguiente se genera el error CS1058.  
  
```csharp  
// CS1058.cs  
// CS1058 expected  
using System.Runtime.CompilerServices;  
  
// the following attribute is set to true by default in the C# compiler  
// set to false in your source code to resolve CS1058  
[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = true)]  
  
class TestClass
{  
   static void Main()
   {  
      try {}  
  
      catch (System.Exception e) {
         System. Console.WriteLine("Caught exception {0}", e);  
      }  
  
      catch {}   // CS1058. This line will never be reached.  
   }  
}  
```
